#!/bin/bash

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# install core and development Python dependencies into the currently activated venv
function install {
    python -m pip install --upgrade pip
    python -m pip install cookiecutter pytest pre-commit
}

# run linting, formatting, and other static code quality tools
function lint {
    pre-commit run --all-files
}

# same as `lint` but with any special considerations for CI
function lint:ci {
    # We skip no-commit-to-branch since that blocks commits to `main`.
    # All merged PRs are commits to `main` so this must be disabled.
    SKIP=no-commit-to-branch pre-commit run --all-files
}

# execute tests that are not marked as `slow`
function test:quick {
    run-tests -m "not slow" ${@:-"$THIS_DIR/tests/"}
}

# (example) ./run.sh test tests/test_states_info.py::test__slow_add
function run-tests {
    python -m pytest ${@:-"$THIS_DIR/tests/"}
}

function test:wheel-locally {
    deactivate || true
    rm -rf test-env || true
    python -m venv test-env
    source test-env/bin/activate
    clean || true
    pip install build
    build
    pip install ./dist/*.whl pytest pytest-cov
    test:ci
    deactivate || true
}

function generate-project {
    cookiecutter ./ --output-dir "$THIS_DIR/sample"
    cd "$THIS_DIR/sample"
    cd "$(ls)"
    git init
    git add --all
    git commit -m "feat: generate repo"
}

# remove all files generated by tests, builds, or operating this codebase
function clean {
    rm -rf dist build coverage.xml test-reports
    find . \
      -type d \
      \( \
        -name "*cache*" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -exec rm -r {} + || true

    find . \
      -type f \
      -name "*.pyc" \
      -not -path "*env/*" \
      -exec rm {} +
}

# export the contents of .env as environment variables
function try-load-dotenv {
    if [ ! -f "$THIS_DIR/.env" ]; then
        echo "no .env file found"
        return 1
    fi

    while read -r line; do
        export "$line"
    done < <(grep -v '^#' "$THIS_DIR/.env" | grep -v '^$')
}

# print all functions in this file
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

# args:
#   REPO_NAME
#   GITHUB_USERNAME
#   IS_PUBLIC
function create-repo-if-not-exists {

    IS_PUBLIC=${IS_PUBLIC:-false}

    if [[ "$IS_PUBLIC" == "true" ]]; then
        PUBLIC_OR_PRIVATE="public"
    else
        PUBLIC_OR_PRIVATE="private"
    fi

    gh repo view "$GITHUB_USERNAME/$REPO_NAME" > /dev/null 2>&1 \
        && echo "Repo already exists, exiting..." \
        && return 0

    echo "Repo does not exist, creating..."
    gh repo create "$GITHUB_USERNAME/$REPO_NAME" --"$PUBLIC_OR_PRIVATE"

    gh repo clone "$GITHUB_USERNAME/$REPO_NAME"

    git config --global user.email "eric.adam.garner@gmail.com"
    git config --global user.name "Eric Adam Garner"

    # Create main branch
    git branch -M main || true

    # Add readme
    echo "# $REPO_NAME" > "$REPO_NAME/README.md"

    # Commit and push to main branch
    cd "$REPO_NAME"
    git add --all
    git commit -m "feat: Add empty README.md"
    if [[ -n "$GH_TOKEN" ]]; then
        git remote set-url origin "https://$GITHUB_USERNAME:$GH_TOKEN@github.com/$GITHUB_USERNAME/$REPO_NAME"
    fi
    git push origin main

}

# args:
#   TEST_PYPI_TOKEN, PROD_PYPI_TOKEN
#   REPO_NAME
#   GITHUB_USERNAME
function configure-repo {
    # Configure github actions secrets
    gh secret set TEST_PYPI_TOKEN \
        --body "$TEST_PYPI_TOKEN" \
        --repo "$GITHUB_USERNAME/$REPO_NAME" \
        && echo "Set pypi tokens"

    gh secret set PROD_PYPI_TOKEN \
        --body "$PROD_PYPI_TOKEN" \
        --repo "$GITHUB_USERNAME/$REPO_NAME"

    # # Proect main branch by enforcing passing build on feature branch before merge (requires pro account)
    # gh api -X PUT "repos/$GITHUB_USERNAME/$REPO_NAME/branches/main/protection" \
    #     -H "Accept: application/vnd.github+json" \
    #     -F "required_status_checks[strict]=true" \
    #     -F "required_status_checks[checks][][context]=check-version-txt" \
    #     -F "required_status_checks[checks][][context]=lint-format-and-static-code-checks" \
    #     -F "required_status_checks[checks][][context]=buid-wheel-and-sdist" \
    #     -F "required_status_checks[checks][][context]=execute-tests" \
    #     -F "required_pull_request_reviews[required_approving_review_count]=1" \
    #     -F "enforce_admins=null" \
    #     -F "restrictions=null" > /dev/null
}

# args:
#   REPO_NAME
#   PACKAGE_IMPORT_NAME
#   GITHUB_USERNAME
#   AUTHOR
#   AUTHOR_EMAIL
function open-pr-with-generated-project {

    # debug
    rm -rf outdir || true
    rm -rf config || true
    rm -rf "$REPO_NAME" || true

    # Clone repository
    gh repo clone "$GITHUB_USERNAME/$REPO_NAME"

    # Delete local repository contents but keep .git file
    mv "$REPO_NAME/.git" "./$REPO_NAME.git.back"
    rm -rf "$REPO_NAME"
    mkdir "$REPO_NAME"
    mv "./$REPO_NAME.git.back" "$REPO_NAME/.git"

    # Generate config file
    mkdir config || true
    CONFIG_FILE_PATH="./config/$REPO_NAME.yaml"
    cat <<EOF > "$CONFIG_FILE_PATH"
default_context:
    repo_name: $REPO_NAME
    package_import_name: $PACKAGE_IMPORT_NAME
    author: $AUTHOR
    author_email: $AUTHOR_EMAIL
EOF
    rm -rf "CONFIG_FILE_PATH"

    # Generate project in outdir
    mkdir outdir || true
    cookiecutter ./ --output-dir=./outdir --no-input --config-file="$CONFIG_FILE_PATH"

    # Move .git into project in outdir
    mv "$REPO_NAME/.git" "./outdir/$REPO_NAME"

    # Checkout new feature branch
    UUID=$(uuidgen)
    UNIQUE_BRANCH_NAME=feat/populating-from-template-${UUID:0:6}

    git config --global user.email "eric.adam.garner@gmail.com"
    git config --global user.name "Eric Adam Garner"

    cd "./outdir/$REPO_NAME"
    git checkout -b "$UNIQUE_BRANCH_NAME"

    # Stage files for linting by pre-commit
    git add --all
    lint:ci || true

    # Restage the files modified by pre-commit
    git add --all

    # Commit changes to feature branch
    git commit -m "feat: generate project from template"

    # Push to remote repository on feature branch
    if [[ -n "$GH_TOKEN" ]]; then
        git remote set-url origin "https://$GITHUB_USERNAME:$GH_TOKEN@github.com/$GITHUB_USERNAME/$REPO_NAME"
    fi
    git push origin "$UNIQUE_BRANCH_NAME"

    # Open pull request into main branch
    gh pr create \
        --title "feat: generate project from template" \
        --body "This PR was generated by python-course-cookiecutter-v2" \
        --base main \
        --head "$UNIQUE_BRANCH_NAME" \
        --repo "$GITHUB_USERNAME/$REPO_NAME"
}

function create-sample-repo {
    gh workflow run .github/workflows/create-or-update-repo.yaml \
        -f repo_name=test-repoZ \
        -f package_import_name=package \
        -f is_public=false \
        --ref main
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
